---
- name: set crontab
  hosts: localhost
  gather_facts: false
  ignore_errors: true
  remote_user: root
  tasks:
  - name: crontab for log
    cron:
      name: add crontab
      minute: "59"
      hour: "23"
      job: "/home/ec2-user/Ansible/cronlog.sh"
      state: present