---
# tasks file for s3

- name: S3 Mount
  hosts: all
  gather_facts: false
  ignore_errors: true

  tasks:
  - name: install epel
    shell: 'sudo amazon-linux-extras install epel -y'

  - name: yum install s3fs-fuse
    yum:
      name: s3fs-fuse
      state: present 

  - name: yum install awscli
    yum:
      name: awscli
      state: present

  - name: yum install Util
    yum:
      name:
        - automake
        - fuse
        - fuse-devel
        - gcc-c++
        - git
        - libcurl-devel
        - libxml2-devel
        - make
        - openssl-devel
        - git
      state: present

  - name: git clone
    git: 
      repo: https://github.com/s3fs-fuse/s3fs-fuse.git
      dest: /home/ec2-user/S3git
      force: yes
      clone: yes

  - name: chown
    file:
      path: /home/ec2-user/S3git
      owner: ec2-user
      group: ec2-user

  - name: chmod
    file:
      path: /home/ec2-user/passwd-s3fs
      mode: 0600  

  - name: mkdir mount point
    file:
      path: /home/ec2-user/S3
      state: directory
      owner: ec2-user
      group: ec2-user
      mode: 0644

  - name: s3 mount
    shell: 
      cmd: 'sudo s3fs final-aws8-log /home/ec2-user/S3 -o use_cache=/tmp -o allow_other -o passwd_file=/home/ec2-user/passwd-s3fs'

- name: S3 mount Check
  hosts: localhost
  gather_facts: false
  ignore_errors: true

  tasks:
  - name: Check
    shell: 'ansible all -m shell -a "df -hT"'
    register: result
  - debug: var=result