---
- name: create directory
  hosts: was
  gather_facts: false
  ignore_errors: true
  tasks:
    - name: create download directory
      file:
        state: directory
        path: /home/ec2-user/apache-tomcat-9.0.56/download

    - name: download tomcat-cluster-redis-session-manager
      get_url:
        url: 'https://github.com/ran-jit/tomcat-cluster-redis-session-manager/releases/download/2.0.4/tomcat-cluster-redis-session-manager.zip'
        dest: '/home/ec2-user/apache-tomcat-9.0.56/download'

    - name: unzip tomcat-cluster-redis-session-manager
      unarchive:
        src: '/home/ec2-user/apache-tomcat-9.0.56/download/tomcat-cluster-redis-session-manager.zip'
        dest: '/home/ec2-user/apache-tomcat-9.0.56/download/'
        remote_src: yes

    - name: copy tomcat-cluster-redis-manager/lib
      copy:
        src: '/home/ec2-user/apache-tomcat-9.0.56/download/tomcat-cluster-redis-session-manager/lib/'
        dest: '/home/ec2-user/apache-tomcat-9.0.56/lib'
        remote_src: yes

    - name: copy tomcat-cluster-redis-manager/conf
      copy:
        src: '/home/ec2-user/apache-tomcat-9.0.56/download/tomcat-cluster-redis-session-manager/conf/'
        dest: '/home/ec2-user/apache-tomcat-9.0.56/conf'
        remote_src: yes

    - name: edit redis-data-cache.properties
      replace:
        path: '/home/ec2-user/apache-tomcat-9.0.56/conf/redis-data-cache.properties'
        regexp: 'redis.hosts=127.0.0.1:6379'
        replace: 'redis.hosts=final-redis.pxq8zj.0001.apn2.cache.amazonaws.com:6379'

    - name: edit web.xml
      replace:
        path: '/home/ec2-user/apache-tomcat-9.0.56/conf/web.xml'
        regexp: '<session-timeout>30</session-timeout>'
        replace: '<session-timeout>60</session-timeout>'

    - name: add web.xml
      lineinfile:
        path: '/home/ec2-user/apache-tomcat-9.0.56/conf/web.xml'
        line: '<distributable/>'

    - name: add context.xml
      lineinfile:
        path: '/home/ec2-user/apache-tomcat-9.0.56/conf/context.xml'
        regexp: '</Context>'
        line: |
          <Valve className="tomcat.request.session.redis.SessionHandlerValve"/>
          <Manager className="tomcat.request.session.redis.SessionManager"/>
          </Context>

    - name: edit server.xml
      lineinfile:
        path: '/home/ec2-user/apache-tomcat-9.0.56/conf/server.xml'
        regexp: 'pattern="%h %l %u %t &quot;%r&quot; %s %b" />'
        line: |
          pattern="%h %l %u %t &quot;%r&quot; %s %b" />
          <Cluster className="org.apache.catalina.ha.tcp.SimpleTcpCluster"/>