---
- name: was log
  hosts: wasa
  gather_facts: false
  ignore_errors: true

  vars:
    date: "{{ lookup('pipe', 'date +%Y-%m-%d') }}"
  
  tasks:
  - name: mkdir S3
    file:
      path: /home/ec2-user/S3/Was-a
      state: directory
      owner: ec2-user
      group: ec2-user
      mode: 0644
  
  - name: chown
    file:
      path: /home/ec2-user/apache-tomcat-9.0.56
      owner: ec2-user
      group: ec2-user

  - name: chmod
    file:
        path: /home/ec2-user/apache-tomcat-9.0.56
        mode: 0777    

  - name: access log
    copy:
      src: '/home/ec2-user/apache-tomcat-9.0.56/logs/catalina.{{ date  }}.log' 
      dest: '/home/ec2-user/S3/Was-a/'
      remote_src: yes

- name: was log
  hosts: wasc
  gather_facts: false
  ignore_errors: true

  vars:
    date: "{{ lookup('pipe', 'date +%Y-%m-%d') }}"  

  tasks:
  - name: mkdir Was-c
    file:
      path: /home/ec2-user/S3/Was-c
      state: directory
      owner: ec2-user
      group: ec2-user
      mode: 0644

  - name: chown
    file:
      path: /home/ec2-user/apache-tomcat-9.0.56
      owner: ec2-user
      group: ec2-user

  - name: chmod
    file:
        path: /home/ec2-user/apache-tomcat-9.0.56
        mode: 0777     

  - name: access log
    copy:
      src: '/home/ec2-user/apache-tomcat-9.0.56/logs/catalina.{{ date  }}.log'
      dest: '/home/ec2-user/S3/Was-c/'
      remote_src: yes
