---
- name: was log
  hosts: wasa
  gather_facts: false
  ignore_errors: true
  tasks:
  - name: mkdir S3
    file:
      path: /home/ec2-user/S3/Was-a
      state: directory
      owner: ec2-user
      group: ec2-user
      mode: 0644
  
  - name: access log
    copy:
      src: '/home/ec2-user/apache-tomcat-9.0.56/logs/catalina.*' 
      dest: '/home/ec2-user/S3/Was-a/catalina.out'
      remote_src: yes

- name: was log
  hosts: wasc
  gather_facts: false
  ignore_errors: true
  tasks:
  - name: mkdir Was-c
    file:
      path: /home/ec2-user/S3/Was-c
      state: directory
      owner: ec2-user
      group: ec2-user
      mode: 0644

  - name: access log
    copy:
      src: '/home/ec2-user/apache-tomcat-9.0.56/logs/catalina.*'
      dest: '/home/ec2-user/S3/Was-c/catalina.out'
      remote_src: yes
 
