---
# tasks file for Web Log

- name: Web Log
  hosts: weba
  gather_facts: false
  ignore_errors: true

  tasks:
  - name: mkdir Web-A
    file:
      path: /home/ec2-user/S3/Web-a
      state: directory
      owner: ec2-user
      group: ec2-user
      mode: 0644
  
  - name: access log
    copy:
      src: '/var/log/httpd/access_log'
      dest: '/home/ec2-user/S3/Web-a/access_log'
      remote_src: yes  

  - name: error log
    copy:
      src: '/var/log/httpd/error_log'
      dest: '/home/ec2-user/S3/Web-a/error_log'
      remote_src: yes 

- name: Web Log
  hosts: webc
  gather_facts: false
  ignore_errors: true

  tasks:
  - name: mkdir Web-C
    file:
      path: /home/ec2-user/S3/Web-c
      state: directory
      owner: ec2-user
      group: ec2-user
      mode: 0644

  - name: access log
    copy:
      src: '/var/log/httpd/access_log'
      dest: '/home/ec2-user/S3/Web-c/access_log'
      remote_src: yes  

  - name: error log
    copy:
      src: '/var/log/httpd/error_log'
      dest: '/home/ec2-user/S3/Web-c/error_log'
      remote_src: yes 